import { exec } from "child_process"
import { promises as fs } from "fs"
import path from "path"
import { rimraf } from "rimraf"
import { Registry } from "../schema"

import { siteConfig } from "../config/sits"
import { registry } from "../registry/index"

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file) => {
      const filePath = typeof file === "string" ? file : file.path
      return `registry/${filePath}`
    })
    
    if (!resolveFiles) {
      continue
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${typeof item.files[0] === "string" ? item.files[0] : item.files[0].path}`
      : ""

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies ?? [])},
    files: [${item.files?.map((file) => {
      const filePath = typeof file === "string" ? file : file.path
      const fullPath = `registry/${filePath}`
      const resolvedFilePath = path.resolve(fullPath)
      
      if (typeof file === "string") {
        return `"${resolvedFilePath}"`
      }
      
      return `{
      path: "${fullPath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`
    }).join(",")}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    meta: ${JSON.stringify(item.meta ?? {})},
  },`
  }

  index += `
  }`

  // Write index file
  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"))
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index)
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items and ensure all required fields are present
  const fixedRegistry = {
    $schema: "https://ui.shadcn.com/schema.json",
    name: registry.name,
    homepage: registry.homepage,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        if (typeof file === "string") {
          return {
            path: file.startsWith("registry/") ? file : `registry/${file}`,
            type: item.type,
          }
        }
        
        return {
          path: file.path.startsWith("registry/") ? file.path : `registry/${file.path}`,
          type: file.type ?? item.type,
          target: file.target ?? undefined,
        }
      })

      // Build the fixed item
      const fixedItem: any = {
        name: item.name,
        type: item.type,
      }

      // Add optional fields only if they exist
      if (item.title) fixedItem.title = item.title
      if (item.description) fixedItem.description = item.description
      if (item.dependencies && item.dependencies.length > 0) {
        fixedItem.dependencies = item.dependencies
      }
      if (item.devDependencies && item.devDependencies.length > 0) {
        fixedItem.devDependencies = item.devDependencies
      }
      if (item.registryDependencies && item.registryDependencies.length > 0) {
        fixedItem.registryDependencies = item.registryDependencies
      }
      if (files && files.length > 0) {
        fixedItem.files = files
      }
      if (item.cssVars) fixedItem.cssVars = item.cssVars
      if (item.meta) fixedItem.meta = item.meta

      return fixedItem
    }),
  }

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), `registry.json`))
  await fs.writeFile(
    path.join(process.cwd(), `registry.json`),
    JSON.stringify(fixedRegistry, null, 2)
  )

  // 3. Copy the registry.json to the www/public/r directory
  const wwwPublicRPath = path.join(process.cwd(), "../www/public/r")
  await fs.mkdir(wwwPublicRPath, { recursive: true })
  await fs.copyFile(
    path.join(process.cwd(), "registry.json"),
    path.join(wwwPublicRPath, "registry.json")
  )

  // 4. Copy the registry.json to the www/public directory
  const wwwPublicPath = path.join(process.cwd(), "../www/public")
  await fs.mkdir(wwwPublicPath, { recursive: true })
  await fs.copyFile(
    path.join(process.cwd(), "registry.json"),
    path.join(wwwPublicPath, "registry.json")
  )
}

type RegistryItem = Registry["items"][number]

type FileEntry = string | { path: string; type?: string; target?: string }

async function readRegistryFilesContents(item: RegistryItem): Promise<string> {
  if (!item.files?.length) return ""

  const paths = item.files
    .map((f: FileEntry) => (typeof f === "string" ? f : f?.path))
    .filter(Boolean)
    .sort() as string[]

  // Read all files in parallel
  const contents = await Promise.all(
    paths.map(async (filePath) => {
      try {
        // Remove 'registry/' prefix if present since we're already in registry dir
        const cleanPath = filePath.replace(/^registry\//, "")
        const content = await fs.readFile(
          path.join(process.cwd(), "registry", cleanPath),
          "utf8"
        )
        return `--- file: ${filePath} ---\n${content.endsWith("\n") ? content : content + "\n"}`
      } catch (error) {
        console.warn(`Warning: Could not read file ${filePath}`)
        return null // Skip missing files
      }
    })
  )

  // Join non-null contents with blank lines between them
  return contents.filter(Boolean).join("\n")
}

function getComponentExamples() {
  const examplesByComponent = new Map<string, string[]>()

  registry.items
    .filter((item) => item.type === "registry:example")
    .forEach((example) => {
      example.registryDependencies?.forEach((dep) => {
        // Remove @gammaui/ prefix if present
        const componentName = dep.replace(/^@gammaui\//, "").split("/").pop()
        if (componentName) {
          if (!examplesByComponent.has(componentName)) {
            examplesByComponent.set(componentName, [])
          }
          examplesByComponent.get(componentName)!.push(example.name)
        }
      })
    })

  return examplesByComponent
}

async function generateLlmsContent() {
  const components = registry.items
    .filter((item) => item.type === "registry:ui")
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((component) => {
      const title = component.title || component.name
      const description = component.description || `The ${title} component.`
      return `- [${title}](${siteConfig.url}/docs/components/${component.name}): ${description}`
    })

  const exampleSet = new Set<string>()
  const examplesList = registry.items
    .filter((item) => item.type === "registry:example")
    .filter((example) => {
      if (exampleSet.has(example.name)) return false
      exampleSet.add(example.name)
      return true
    })
    .map((example) => {
      const title = example.title || example.name
      const firstFile = example.files?.[0]
      const filePath = typeof firstFile === "string" ? firstFile : firstFile?.path || ""
      const url = filePath
        ? `${siteConfig.links.github}/blob/main/registry/${filePath}`
        : siteConfig.links.github
      return `- [${title}](${url}): Example usage`
    })

  return [
    `# ${siteConfig.name}`,
    "",
    `> ${siteConfig.description}`,
    "",
    "This file provides LLM-friendly entry points to documentation and examples.",
    "",
    "## Components",
    "",
    ...components,
    "",
    "## Examples",
    "",
    ...examplesList,
    "",
    "## Optional",
    "",
    `- [Repository](${siteConfig.links.github}): Source code and issues`,
    `- [Sitemap](${siteConfig.url}/sitemap.xml): Indexable pages`,
  ].join("\n")
}

async function generateLlmsFullContent(
  examplesByComponent: Map<string, string[]>
) {
  const components = registry.items
    .filter((item) => item.type === "registry:ui")
    .sort((a, b) => a.name.localeCompare(b.name))

  const componentContents = await Promise.all(
    components.map(async (component) => {
      const title = component.title || component.name
      const description = component.description || `The ${title} component.`

      let content = [
        `===== COMPONENT: ${component.name} =====`,
        `Title: ${title}`,
        `Description: ${description}`,
        "",
        await readRegistryFilesContents(component),
      ].join("\n")

      // Add examples for this component
      const relatedExamples = examplesByComponent.get(component.name) || []
      for (const exampleName of relatedExamples) {
        const example = registry.items.find((e) => e.name === exampleName)
        if (example) {
          const exTitle = example.title || example.name
          content += [
            "",
            "",
            `===== EXAMPLE: ${exampleName} =====`,
            `Title: ${exTitle}`,
            "",
            await readRegistryFilesContents(example),
          ].join("\n")
        }
      }

      return content
    })
  )

  return componentContents.join("\n\n\n")
}

async function buildLlmsFiles() {
  const examplesByComponent = getComponentExamples()

  const [minContent, fullContent] = await Promise.all([
    generateLlmsContent(),
    generateLlmsFullContent(examplesByComponent),
  ])

  const publicDir = path.join(process.cwd(), "public")
  await fs.mkdir(publicDir, { recursive: true })

  await Promise.all([
    fs.writeFile(path.join(publicDir, "llms.txt"), minContent, "utf8"),
    fs.writeFile(path.join(publicDir, "llms-full.txt"), fullContent, "utf8"),
  ])

  console.log("  📝 Created llms.txt")
  console.log("  📝 Created llms-full.txt")
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const buildProcess = exec(`pnpm shadcn:build`)

    buildProcess.stdout?.on('data', (data) => {
      console.log(data.toString().trim())
    })

    buildProcess.stderr?.on('data', (data) => {
      console.error(data.toString().trim())
    })

    buildProcess.on("exit", (code) => {
      if (code === 0) {
        resolve(undefined)
      } else {
        reject(new Error(`Process exited with code ${code}`))
      }
    })

    buildProcess.on("error", (error) => {
      reject(error)
    })
  })
}

try {
  console.log("🏗️ Building registry/__index__.tsx...")
  await buildRegistryIndex()
  console.log("✅ Registry index built successfully")

  console.log("\n💅 Building registry.json...")
  await buildRegistryJsonFile()
  console.log("✅ Registry JSON file built successfully")

  console.log("\n🧠 Building llms files...")
  await buildLlmsFiles()
  console.log("✅ llms files built successfully")

  console.log("\n🔨 Building registry...")
  await buildRegistry()
  console.log("✅ Registry build completed")

  console.log("\n🎉 All build steps completed successfully!")
} catch (error) {
  console.error("\n❌ Build failed with error:")
  console.error(error)
  if (error instanceof Error) {
    console.error("Error stack:", error.stack)
  }
  process.exit(1)
}