/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: {},
  },
  "live-waveform": {
    name: "live-waveform",
    description: "A customizable live audio waveform visualizer using the Web Audio API.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/live-waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/live-waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "live-waveform"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "support-box": {
    name: "support-box",
    description: "A collapsible animated support widget for quick help actions using Framer Motion.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/support-box.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/support-box.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "support-box"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "overlay-button": {
    name: "overlay-button",
    description: "An animated gradient button using Framer Motion with looping motion and spring transitions.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/overlay-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/overlay-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "overlay-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "border-button": {
    name: "border-button",
    description: "A reactive border animation button that follows cursor movement using Framer Motion and CSS masks.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/border-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/border-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "border-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "wavy-text-block": {
    name: "wavy-text-block",
    description: "A scroll-triggered wavy text animation component that creates flowing motion effects using Framer Motion and scroll context.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/wavy-text-block.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/wavy-text-block.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wavy-text-block"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "inverted-cursor": {
    name: "inverted-cursor",
    description: "A smooth, animated custom cursor component with blend mode effects.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/inverted-cursor.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/inverted-cursor.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "inverted-cursor"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "pixel-button": {
    name: "pixel-button",
    description: "A pixelated button animation effect built with Tailwind CSS and React.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/pixel-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/pixel-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pixel-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "plasma": {
    name: "plasma",
    description: "A mesmerizing plasma shader animation rendered with WebGL, perfect for dynamic backgrounds and previews.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/plasma.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/plasma.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "plasma"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "radial-intro": {
    name: "radial-intro",
    description: "A dynamic radial orbit animation built with Motion and React, featuring upright spinning image nodes.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/radial-intro.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/radial-intro.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "radial-intro"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-cloud": {
    name: "logo-cloud",
    description: "A responsive logo grid component supporting dark mode, decorations, and flexible layout.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/logo-cloud.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/logo-cloud.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-cloud"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "wave-path": {
    name: "wave-path",
    description: "A dynamic interactive SVG wave component that responds to pointer movement.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/wave-path.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/wave-path.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wave-path"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "magnetize-button": {
    name: "magnetize-button",
    description: "A magnetic particle-attraction button built with Framer Motion.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/magnetize-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/magnetize-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "magnetize-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "text-roll": {
    name: "text-roll",
    description: "A rolling hover-animated text component built with Motion One.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/text-roll.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/text-roll.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "text-roll"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "activity-dropdown": {
    name: "activity-dropdown",
    description: "A modern activity/notification dropdown with smooth animations and responsive motion.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/activity-dropdown.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/activity-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "activity-dropdown"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "badge": {
    name: "badge",
    description: "A flexible and customizable Badge component for labels, statuses, and indicators.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "badge"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "animated-list": {
    name: "animated-list",
    description: "A dynamic list component with smooth animations that forms a column and scrolls through items continuously.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/animated-list.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/animated-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-list"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-timeline": {
    name: "logo-timeline",
    description: "A multi-row infinitely scrolling logo timeline built with Motion One, supporting hover-activated animations and row grouping.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/logo-timeline.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/logo-timeline.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-timeline"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-loop": {
    name: "logo-loop",
    description: "A looping logo marquee component with horizontal and vertical motion, hover effects, fading edges, and responsive behavior.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/logo-loop.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/logo-loop.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-loop"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "pricing-interaction": {
    name: "pricing-interaction",
    description: "An interactive pricing switcher with animated numbers, selectable plans, and monthly/yearly billing modes.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/pricing-interaction.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/pricing-interaction.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pricing-interaction"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "rest-api": {
    name: "rest-api",
    description: "A beautifully animated REST API visualization component with SVG paths, glowing lights, badges, and interactive motion effects.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/rest-api.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/rest-api.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "rest-api"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "macbook-keyboard": {
    name: "macbook-keyboard",
    description: "Interactive animated MacBook keyboard component.",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "registry/gammaui/macbook-keyboard.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/gammaui/macbook-keyboard.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "macbook-keyboard"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "live-waveform-demo": {
    name: "live-waveform-demo",
    description: "A customizable live audio waveform visualizer using the Web Audio API.",
    type: "registry:example",
    registryDependencies: ["@gammaui/live-waveform"],
    files: [{
      path: "registry/example/live-waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/live-waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "live-waveform-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "support-box-demo": {
    name: "support-box-demo",
    description: "An expandable and animated support widget with quick help actions using Framer Motion.",
    type: "registry:example",
    registryDependencies: ["@gammaui/support-box"],
    files: [{
      path: "registry/example/support-box-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/support-box-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "support-box-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "overlay-button-demo": {
    name: "overlay-button-demo",
    description: "A looping animated gradient button using Framer Motion’s spring transitions for smooth motion effects.",
    type: "registry:example",
    registryDependencies: ["@gammaui/overlay-button"],
    files: [{
      path: "registry/example/overlay-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/overlay-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "overlay-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "border-button-demo": {
    name: "border-button-demo",
    description: "An interactive button that animates its border dynamically based on cursor position using Framer Motion.",
    type: "registry:example",
    registryDependencies: ["@gammaui/border-button"],
    files: [{
      path: "registry/example/border-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/border-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "border-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "wavy-text-block-demo": {
    name: "wavy-text-block-demo",
    description: "An example demonstrating the Wavy Block scroll-triggered animation with multiple text lines.",
    type: "registry:example",
    registryDependencies: ["@gammaui/wavy-text-block"],
    files: [{
      path: "registry/example/wavy-text-block-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/wavy-text-block-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wavy-text-block-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "inverted-cursor-demo": {
    name: "inverted-cursor-demo",
    description: "A smooth, animated custom cursor component with blend mode effects.",
    type: "registry:example",
    registryDependencies: ["@gammaui/inverted-cursor"],
    files: [{
      path: "registry/example/inverted-cursor-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/inverted-cursor-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "inverted-cursor-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "pixel-button-demo": {
    name: "pixel-button-demo",
    description: "A pixelated button animation effect built with Tailwind CSS and React.",
    type: "registry:example",
    registryDependencies: ["@gammaui/pixel-button"],
    files: [{
      path: "registry/example/pixel-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/pixel-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pixel-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "plasma-demo": {
    name: "plasma-demo",
    description: "A mesmerizing plasma shader animation rendered with WebGL, perfect for dynamic backgrounds and previews.",
    type: "registry:example",
    registryDependencies: ["@gammaui/plasma"],
    files: [{
      path: "registry/example/plasma-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/plasma-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "plasma-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "radial-intro-demo": {
    name: "radial-intro-demo",
    description: "A rotating radial orbit animation demo showcasing spinning profile images.",
    type: "registry:example",
    registryDependencies: ["radial-intro"],
    files: [{
      path: "registry/example/radial-intro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/radial-intro-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "radial-intro-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-cloud-demo": {
    name: "logo-cloud-demo",
    description: "A responsive logo grid demo showcasing brand logos with optional plus icons.",
    type: "registry:example",
    registryDependencies: ["logo-cloud"],
    files: [{
      path: "registry/example/logo-cloud-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-cloud-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-cloud-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "wave-path-demo": {
    name: "wave-path-demo",
    description: "An interactive SVG wave animation that reacts to cursor movement.",
    type: "registry:example",
    registryDependencies: ["@gammaui/wave-path"],
    files: [{
      path: "registry/example/wave-path-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/wave-path-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "wave-path-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "magnetize-button-demo": {
    name: "magnetize-button-demo",
    description: "An interactive demo showcasing the Magnetize Button component with particle attraction effects.",
    type: "registry:example",
    registryDependencies: ["@gammaui/magnetize-button"],
    files: [{
      path: "registry/example/magnetize-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/magnetize-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "magnetize-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "text-roll-demo": {
    name: "text-roll-demo",
    description: "An interactive demo showcasing the TextRoll hover animation component.",
    type: "registry:example",
    registryDependencies: ["@gammaui/text-roll"],
    files: [{
      path: "registry/example/text-roll-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/text-roll-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "text-roll-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "activity-dropdown-demo": {
    name: "activity-dropdown-demo",
    description: "A demo showcasing the animated ActivityDropdown component with staggered item reveal.",
    type: "registry:example",
    registryDependencies: ["@gammaui/activity-dropdown"],
    files: [{
      path: "registry/example/activity-dropdown-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/activity-dropdown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "activity-dropdown-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "badge-demo": {
    name: "badge-demo",
    description: "A demo showcasing the GammaUI Badge component with customizable colors, sizes, and variants.",
    type: "registry:example",
    registryDependencies: ["@gammaui/badge"],
    files: [{
      path: "registry/example/badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "badge-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "animated-list-demo": {
    name: "animated-list-demo",
    description: "A demo showcasing the Animated List component with smooth formation and scrolling animations.",
    type: "registry:example",
    registryDependencies: ["@gammaui/animated-list"],
    files: [{
      path: "registry/example/animated-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "animated-list-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-timeline-demo": {
    name: "logo-timeline-demo",
    description: "A demo showcasing the animated multi-row Logo Timeline component with infinite scrolling and staggered item motion.",
    type: "registry:example",
    registryDependencies: ["@gammaui/logo-timeline"],
    files: [{
      path: "registry/example/logo-timeline-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-timeline-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-timeline-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-timeline-demo-2": {
    name: "logo-timeline-demo-2",
    description: "A demo showcasing the animated multi-row Logo Timeline component with infinite scrolling and staggered item motion.",
    type: "registry:example",
    registryDependencies: ["@gammaui/logo-timeline"],
    files: [{
      path: "registry/example/logo-timeline-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-timeline-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-timeline-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "logo-loop-demo": {
    name: "logo-loop-demo",
    description: "A looping logo marquee component with horizontal and vertical motion, hover effects, fading edges, and responsive behavior.",
    type: "registry:example",
    registryDependencies: ["@gammaui/logo-loop"],
    files: [{
      path: "registry/example/logo-loop-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-loop-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logo-loop-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "pricing-interaction-demo": {
    name: "pricing-interaction-demo",
    description: "An interactive pricing switcher with animated numbers, selectable plans, and monthly/yearly billing modes.",
    type: "registry:example",
    registryDependencies: ["@gammaui/pricing-interaction"],
    files: [{
      path: "registry/example/pricing-interaction-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/pricing-interaction-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "pricing-interaction-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "rest-api-demo": {
    name: "rest-api-demo",
    description: "A beautifully animated REST API visualization component with SVG paths, glowing lights, badges, and interactive motion effects.",
    type: "registry:example",
    registryDependencies: ["@gammaui/rest-api"],
    files: [{
      path: "registry/example/rest-api-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/rest-api-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "rest-api-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "macbook-keyboard-demo": {
    name: "macbook-keyboard-demo",
    description: "Interactive animated MacBook keyboard component.",
    type: "registry:example",
    registryDependencies: ["@gammaui/macbook-keyboard"],
    files: [{
      path: "registry/example/macbook-keyboard-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/macbook-keyboard-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "macbook-keyboard-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {},
  },
  }