export const siteConfig = {
  name: "Gamma UI",
  url: "https://gammaui.com",
  ogImage: "https://gammaui.com/og",
  description:
    "Beautifully designed landing page components built with React & Tailwind CSS.",
  links: {
    twitter: "https://x.com/mazyar_kawa",
    github: "https://github.com/mazyar-kawa/gamma-ui",
  },
  keywords: [
    "GammaUI",
    "UI Library",
    "Component Library",
    "React Components",
    "Next.js",
    "Tailwind CSS",
    "Open Source",
    "Frontend",
    "Design System",
    "Mazyar Kawa",
    "GammaUI by Aman",
    "Copy and Paste Components",
    "Developer Tools",
    "Frontend Engineer",
    "Beautiful UI",
    "React UI Kit",
    "Free React Components",
    "Open Source UI Kit",
    "Tailwind UI Components",
    "Headless UI",
    "Reusable React Components",
    "UI Templates",
    "Accessible React Components",
    "Copy-Paste UI",
    "Next.js Component Library",
    "Open Source Developer Tools",
    "Frontend Design System",
    "Minimal UI Kit",
    "Clean React UI",
  ],
  authors: [{ name: "Mazyar Kawa", url: "https://mazyar.dev" }],
  creator: "Mazyar Kawa",
  publisher: "Mazyar Kawa",
}

export type SiteConfig = typeof siteConfig
